config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :practitioners
  resources :practices
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :practice
  belongs_to :practitioner
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :practice
end

app/models/practice.rb
class Practice < ApplicationRecord
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
  belongs_to :practice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to @appointment, notice: "Appointment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /appointments/1
  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: "Appointment was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy!
    redirect_to appointments_url, notice: "Appointment was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:practice_id, :start, :end, :title, :description, :practitioner_id, :patient_id)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: "Patient was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /patients/1
  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: "Patient was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /patients/1
  def destroy
    @patient.destroy!
    redirect_to patients_url, notice: "Patient was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :phone, :phone2, :address, :address2, :cp, :town, :email, :practice_id)
    end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :set_practice, only: %i[ show edit update destroy ]

  # GET /practices
  def index
    @practices = Practice.all
  end

  # GET /practices/1
  def show
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit
  end

  # POST /practices
  def create
    @practice = Practice.new(practice_params)

    if @practice.save
      redirect_to @practice, notice: "Practice was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /practices/1
  def update
    if @practice.update(practice_params)
      redirect_to @practice, notice: "Practice was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /practices/1
  def destroy
    @practice.destroy!
    redirect_to practices_url, notice: "Practice was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def practice_params
      params.require(:practice).permit(:name, :address, :address2, :cp, :town, :phone, :phone2, :email)
    end
end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  before_action :set_practitioner, only: %i[ show edit update destroy ]

  # GET /practitioners
  def index
    @practitioners = Practitioner.all
  end

  # GET /practitioners/1
  def show
  end

  # GET /practitioners/new
  def new
    @practitioner = Practitioner.new
  end

  # GET /practitioners/1/edit
  def edit
  end

  # POST /practitioners
  def create
    @practitioner = Practitioner.new(practitioner_params)

    if @practitioner.save
      redirect_to @practitioner, notice: "Practitioner was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /practitioners/1
  def update
    if @practitioner.update(practitioner_params)
      redirect_to @practitioner, notice: "Practitioner was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /practitioners/1
  def destroy
    @practitioner.destroy!
    redirect_to practitioners_url, notice: "Practitioner was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practitioner
      @practitioner = Practitioner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def practitioner_params
      params.require(:practitioner).permit(:first_name, :last_name, :phone, :email, :practice_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Practice:</strong>
    <%= appointment.practice_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start:</strong>
    <%= appointment.start %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End:</strong>
    <%= appointment.end %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= appointment.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= appointment.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Practitioner:</strong>
    <%= appointment.practitioner_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Patient:</strong>
    <%= appointment.patient_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this appointment", appointment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this appointment", edit_appointment_path(appointment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, class: "contents") do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :practice_id %>
    <%= form.text_field :practice_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start %>
    <%= form.datetime_field :start, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end %>
    <%= form.datetime_field :end, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :practitioner_id %>
    <%= form.text_field :practitioner_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing appointment</h1>

  <%= render "form", appointment: @appointment %>

  <%= link_to "Show this appointment", @appointment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to appointments", appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/appointments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Appointments</h1>
    <%= link_to "New appointment", new_appointment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="appointments" class="min-w-full">
    <%= render @appointments %>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New appointment</h1>

  <%= render "form", appointment: @appointment %>

  <%= link_to "Back to appointments", appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/appointments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @appointment %>

    <%= link_to "Edit this appointment", edit_appointment_path(@appointment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this appointment", appointment_path(@appointment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to appointments", appointments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tofi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, class: "contents") do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone2 %>
    <%= form.text_field :phone2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address2 %>
    <%= form.text_field :address2, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cp %>
    <%= form.text_field :cp, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :town %>
    <%= form.text_field :town, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :practice_id %>
    <%= form.text_field :practice_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= patient.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= patient.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= patient.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone2:</strong>
    <%= patient.phone2 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= patient.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address2:</strong>
    <%= patient.address2 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cp:</strong>
    <%= patient.cp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Town:</strong>
    <%= patient.town %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= patient.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Practice:</strong>
    <%= patient.practice_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this patient", patient, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this patient", edit_patient_path(patient), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/patients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Show this patient", @patient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Patients</h1>
    <%= link_to "New patient", new_patient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="patients" class="min-w-full">
    <%= render @patients %>
  </div>
</div>

app/views/patients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New patient</h1>

  <%= render "form", patient: @patient %>

  <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/patients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @patient %>

    <%= link_to "Edit this patient", edit_patient_path(@patient), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this patient", patient_path(@patient), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to patients", patients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/practices/_practice.html.erb
<div id="<%= dom_id practice %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= practice.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= practice.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address2:</strong>
    <%= practice.address2 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cp:</strong>
    <%= practice.cp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Town:</strong>
    <%= practice.town %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= practice.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone2:</strong>
    <%= practice.phone2 %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= practice.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this practice", practice, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this practice", edit_practice_path(practice), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/practices/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing practice</h1>

  <%= render "form", practice: @practice %>

  <%= link_to "Show this practice", @practice, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to practices", practices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/practices/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Practices</h1>
    <%= link_to "New practice", new_practice_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="practices" class="min-w-full">
    <%= render @practices %>
  </div>
</div>

app/views/practices/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New practice</h1>

  <%= render "form", practice: @practice %>

  <%= link_to "Back to practices", practices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/practices/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @practice %>

    <%= link_to "Edit this practice", edit_practice_path(@practice), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this practice", practice_path(@practice), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to practices", practices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/practitioners/_practitioner.html.erb
<div id="<%= dom_id practitioner %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= practitioner.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= practitioner.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= practitioner.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= practitioner.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Practice:</strong>
    <%= practitioner.practice_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this practitioner", practitioner, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this practitioner", edit_practitioner_path(practitioner), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/practitioners/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing practitioner</h1>

  <%= render "form", practitioner: @practitioner %>

  <%= link_to "Show this practitioner", @practitioner, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to practitioners", practitioners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/practitioners/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Practitioners</h1>
    <%= link_to "New practitioner", new_practitioner_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="practitioners" class="min-w-full">
    <%= render @practitioners %>
  </div>
</div>

app/views/practitioners/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New practitioner</h1>

  <%= render "form", practitioner: @practitioner %>

  <%= link_to "Back to practitioners", practitioners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/practitioners/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @practitioner %>

    <%= link_to "Edit this practitioner", edit_practitioner_path(@practitioner), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this practitioner", practitioner_path(@practitioner), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to practitioners", practitioners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>